#!/usr/bin/env node
// 在 production build 前,從環境變數產生 public/config.js。
//
// 用法:由 npm 的 prebuild script 自動呼叫:
//   $ npm run build
//   → 先跑 generate-config.js
//   → 再跑 vite build
//
// 在 Cloudflare Pages 設定環境變數:
//   SUPABASE_URL, SUPABASE_ANON_KEY, EMAIL_DOMAIN, SITE_URL
//
// 缺任何一個必要欄位會直接 exit 1,讓 build 失敗(避免出包出 placeholder)。

import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = resolve(__dirname, '..');

const REQUIRED = ['SUPABASE_URL', 'SUPABASE_ANON_KEY', 'EMAIL_DOMAIN', 'SITE_URL'];

function fail(msg) {
  console.error(`[generate-config] ✗ ${msg}`);
  process.exit(1);
}

const missing = REQUIRED.filter((k) => !process.env[k]);
if (missing.length > 0) {
  fail(
    `缺少必要環境變數:${missing.join(', ')}\n` +
    `  本機開發請改用 public/config.local.js(複製自 example)\n` +
    `  CI / Cloudflare Pages 請在 dashboard 設定這些變數。`
  );
}

// 安全檢查:絕對不可放 service_role key
const key = process.env.SUPABASE_ANON_KEY;
if (key.startsWith('sbp_')) {
  fail('SUPABASE_ANON_KEY 看起來是 sbp_ secret key,請改用 anon public key (eyJ... JWT)');
}
if (!key.startsWith('eyJ') && !key.startsWith('sb_publishable_')) {
  fail('SUPABASE_ANON_KEY 格式異常,應為 eyJ... 開頭的 JWT(legacy)或 sb_publishable_ 開頭');
}
// 粗略偵測 service_role JWT(payload 中含 "service_role")
if (key.startsWith('eyJ')) {
  try {
    const payload = JSON.parse(Buffer.from(key.split('.')[1], 'base64').toString('utf8'));
    if (payload.role === 'service_role') {
      fail('SUPABASE_ANON_KEY 是 service_role key!絕對不可放在前端,請改用 anon public key。');
    }
  } catch {
    fail('SUPABASE_ANON_KEY 不是合法的 JWT,請檢查');
  }
}

const config = {
  SUPABASE_URL: process.env.SUPABASE_URL,
  SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY,
  EMAIL_DOMAIN: process.env.EMAIL_DOMAIN,
  SITE_URL: process.env.SITE_URL
};

const content = `// AUTO-GENERATED by scripts/generate-config.js — do not edit by hand.
// Generated at ${new Date().toISOString()} from environment variables.
window.CONFIG = ${JSON.stringify(config, null, 2)};
`;

const outPath = resolve(PROJECT_ROOT, 'public/config.js');
writeFileSync(outPath, content, 'utf8');
console.log(`[generate-config] ✓ 已寫入 ${outPath}`);
console.log(`  URL:          ${config.SUPABASE_URL}`);
console.log(`  EMAIL_DOMAIN: ${config.EMAIL_DOMAIN}`);
console.log(`  SITE_URL:     ${config.SITE_URL}`);
console.log(`  ANON_KEY:     ${key.slice(0, 24)}…(已驗證為 anon)`);
