-- ═══════════════════════════════════════════════════════════════════
-- ChemWordle 題庫擴充:batch4 + batch5
--
-- 由 scripts/generate-batch-sql.js 自動產生,請勿手動編輯。
-- 要改題目請改 word-candidates-batch4.md / batch5.md 後重跑生成器。
--
-- 每日題庫:233 題
-- 訪客池  :40 題
-- 合計    :273 題
--
-- 用法:整段複製貼到 Supabase SQL Editor → Run。
-- 注意:answer 會由既有 trigger 自動同步進 valid_words,不必另外處理。
--
-- 全部包在一個交易裡:任何一步失敗都會整個 rollback,不會留下半套資料。
-- 開頭有防呆檢查,若有答案已存在於題庫會中止並列出是哪些字。
-- ═══════════════════════════════════════════════════════════════════

begin;


-- ─── 防呆:若有任何答案已存在就中止 ───
do $$
declare v_dup text;
begin
  select string_agg(answer, ', ' order by answer) into v_dup
  from public.daily_puzzles
  where upper(answer) in (
    'OCTANE', 'NONANE', 'DECANE', 'ALKANE', 'ALKYL', 'PROPYL', 'BUTYL', 'PENTYL',
    'HEXYL', 'OCTYL', 'ALLYL', 'VINYL', 'ETHYL', 'ARENE', 'ALKOXY', 'ACETYL',
    'FORMYL', 'BENZYL', 'PHENYL', 'NITRO', 'AMINO', 'THIOL', 'AZIDE', 'IMINE',
    'ACETAL', 'SILANE', 'BORANE', 'TRIOL', 'XYLENE', 'CRESOL', 'FURAN', 'PURINE',
    'DIMER', 'TRIMER', 'ACETIC', 'FORMIC', 'OXALIC', 'CITRIC', 'LACTIC', 'RIBOSE',
    'XYLOSE', 'HEXOSE', 'STEROL', 'GLOBIN', 'PEPSIN', 'LIPASE', 'CODON', 'STARCH',
    'PECTIN', 'CHITIN', 'LYSINE', 'SERINE', 'VALINE', 'NYLON', 'RAYON', 'RESIN',
    'LATEX', 'FIBER', 'EPOXY', 'DOPANT', 'WAFER', 'SINTER', 'ANNEAL', 'ZIRCON',
    'RUTILE', 'GARNET', 'GYPSUM', 'HALITE', 'PYRITE', 'BARIUM', 'CERIUM', 'CESIUM',
    'INDIUM', 'RADIUM', 'RADON', 'OSMIUM', 'BOSON', 'QUARK', 'SIGMA', 'DELTA',
    'ALPHA', 'GAMMA', 'LAMBDA', 'DECAY', 'HYBRID', 'REDOX', 'REFLUX', 'QUENCH',
    'ELUTE', 'DECANT', 'FILTER', 'PURIFY', 'DIGEST', 'DISTIL', 'CRACK', 'REFORM',
    'SALINE', 'BRINE', 'SLURRY', 'ALKALI', 'BORATE', 'MOLTEN', 'FROZEN', 'DENSE',
    'INERT', 'BASIC', 'TOXIC', 'STABLE', 'PLANAR', 'LINEAR', 'PHASE', 'TRANS',
    'ASSAY', 'BLANK', 'PURITY', 'NORMAL', 'PROBE', 'SENSOR', 'BEAKER', 'FLASK',
    'BURNER', 'MORTAR', 'PESTLE', 'FUNNEL', 'PIPET', 'BURET', 'ANION', 'OCTET',
    'NOBLE', 'GROUP', 'PERIOD', 'SHELL', 'ORBIT', 'MATTER', 'LEVEL', 'LEWIS',
    'ANGLE', 'LENGTH', 'MOMENT', 'FERMI', 'FORMAL', 'BORIDE', 'BORAX', 'POTASH',
    'CHALK', 'BRASS', 'BRONZE', 'SOLDER', 'LITMUS', 'DONOR', 'STRONG', 'EXCESS',
    'LIMIT', 'ORDER', 'CHAIN', 'AGENT', 'JOULE', 'KELVIN', 'PASCAL', 'NEWTON',
    'HERTZ', 'TESLA', 'DEBYE', 'GAUSS', 'FARAD', 'AMPERE', 'DEGREE', 'RAMAN',
    'ABSORB', 'EXCITE', 'GROUND', 'SHIFT', 'FIELD', 'SIGNAL', 'NOISE', 'COLUMN',
    'MATRIX', 'TORCH', 'SAMPLE', 'INJECT', 'DETECT', 'TRACE', 'DILUTE', 'STOCK',
    'WEIGH', 'PLATE', 'CHARGE', 'PURGE', 'RINSE', 'SEPTUM', 'SPIKE', 'CURVE',
    'SLOPE', 'RANGE', 'GIBBS', 'SYSTEM', 'STATE', 'CYCLE', 'FREEZE', 'TEMPER',
    'IDEAL', 'FLUID', 'ACTIVE', 'ADSORB', 'DESORB', 'UPTAKE', 'POISON', 'BUBBLE',
    'CUBIC', 'PLANE', 'FACET', 'GRAIN', 'DOMAIN', 'DEFECT', 'ORTHO', 'GLASSY',
    'BLEND', 'CURING', 'MOULD', 'TOUGH', 'RIGID', 'CREEP', 'POLYOL', 'GLASS',
    'STEEL', 'CEMENT', 'ENAMEL', 'LAYER', 'PELLET', 'POWDER', 'FLAKE', 'SHEET',
    'CRUDE', 'DIESEL', 'PETROL', 'REFINE', 'OLEFIN', 'URACIL', 'HELIX', 'STRAND',
    'GENOME', 'ACTIN', 'MYOSIN', 'LIGASE', 'KINASE', 'OLEIC', 'OLEATE', 'MOIETY',
    'BRANCH', 'CYCLIC', 'MIXING', 'AGING', 'SETTLE', 'IMPURE', 'DIODE', 'WASTE',
    'BIOGAS', 'SOLAR', 'SLUDGE', 'SEWAGE', 'LEACH', 'RUNOFF', 'BENIGN', 'RENEW',
    'REUSE', 'TOXIN', 'HAZARD', 'SAFETY', 'EXPOSE', 'DOSAGE', 'INTAKE', 'SMOKE',
    'DRYING'
  );
  if v_dup is not null then
    raise exception '這些答案已存在於題庫,請先從候選 md 移除後重跑生成器:%', v_dup;
  end if;
end$$;


-- ─── 每日題庫(233 題,佔位日期自 2026-07-05 起) ───
insert into public.daily_puzzles
  (puzzle_date, answer, category, is_active, zh_name, zh_description, en_description)
values
  ('2026-07-05', 'NONANE', 'organic', true, '壬烷', 'C₉H₂₀,九碳直鏈烷烴。', 'C₉H₂₀; a nine-carbon straight-chain alkane.'),
  ('2026-07-06', 'DECANE', 'organic', true, '癸烷', 'C₁₀H₂₂,十碳烷烴,柴油成分之一。', 'C₁₀H₂₂; ten-carbon alkane, a diesel component.'),
  ('2026-07-07', 'ALKYL', 'organic', true, '烷基', '烷烴少一個氫的基團,如甲基 –CH₃。', 'An alkane minus one hydrogen, e.g., methyl –CH₃.'),
  ('2026-07-08', 'PROPYL', 'organic', true, '丙基', '–C₃H₇,三碳烷基。', '–C₃H₇; a three-carbon alkyl group.'),
  ('2026-07-09', 'BUTYL', 'organic', true, '丁基', '–C₄H₉,四碳烷基,有正/異/二級/三級四種。', '–C₄H₉; four-carbon alkyl with n-, iso-, sec-, tert- forms.'),
  ('2026-07-10', 'PENTYL', 'organic', true, '戊基', '–C₅H₁₁,五碳烷基(舊稱 amyl)。', '–C₅H₁₁; five-carbon alkyl (formerly "amyl").'),
  ('2026-07-11', 'HEXYL', 'organic', true, '己基', '–C₆H₁₃,六碳烷基。', '–C₆H₁₃; a six-carbon alkyl group.'),
  ('2026-07-12', 'OCTYL', 'organic', true, '辛基', '–C₈H₁₇,八碳烷基,界面活性劑常見。', '–C₈H₁₇; eight-carbon alkyl, common in surfactants.'),
  ('2026-07-13', 'ALLYL', 'organic', true, '烯丙基', 'CH₂=CH–CH₂–,含雙鍵的三碳基團。', 'CH₂=CH–CH₂–; three-carbon group containing a double bond.'),
  ('2026-07-14', 'VINYL', 'organic', true, '乙烯基', 'CH₂=CH–,PVC(聚氯乙烯)的 V 就是它。', 'CH₂=CH–; the "V" in PVC (polyvinyl chloride).'),
  ('2026-07-15', 'ETHYL', 'organic', true, '乙基', '–C₂H₅,兩碳烷基。', '–C₂H₅; a two-carbon alkyl group.'),
  ('2026-07-16', 'ARENE', 'organic', true, '芳香烴', '含苯環的芳香族碳氫化合物總稱。', 'General term for aromatic hydrocarbons containing a benzene ring.'),
  ('2026-07-17', 'ALKOXY', 'organic', true, '烷氧基', '–OR,醚類的組成基團。', '–OR; the group that makes up ethers.'),
  ('2026-07-18', 'ACETYL', 'organic', true, '乙醯基', 'CH₃CO–,阿斯匹靈、乙醯輔酶 A 都含此基。', 'CH₃CO–; found in aspirin and acetyl-CoA.'),
  ('2026-07-19', 'FORMYL', 'organic', true, '甲醯基', 'HCO–,醛類的官能基。', 'HCO–; the functional group of aldehydes.'),
  ('2026-07-20', 'BENZYL', 'organic', true, '苄基', 'C₆H₅CH₂–,苯環接一個亞甲基。', 'C₆H₅CH₂–; a benzene ring attached to a methylene.'),
  ('2026-07-21', 'AMINO', 'organic', true, '胺基', '–NH₂,胺基酸的名字由來。', '–NH₂; the group that gives amino acids their name.'),
  ('2026-07-22', 'THIOL', 'organic', true, '硫醇', '–SH,有臭味,瓦斯加臭劑的成分。', '–SH; smelly, used as the odorant added to natural gas.'),
  ('2026-07-23', 'AZIDE', 'organic', true, '疊氮化物', '含 –N₃;安全氣囊的疊氮化鈉分解產生氮氣。', 'Contains –N₃; sodium azide in airbags decomposes to N₂.'),
  ('2026-07-24', 'IMINE', 'organic', true, '亞胺', '含 C=N 雙鍵,醛酮與胺反應的產物。', 'Contains C=N; formed from aldehydes/ketones plus amines.'),
  ('2026-07-25', 'ACETAL', 'organic', true, '縮醛', '醛與兩分子醇的產物,醣類環化的關鍵。', 'From an aldehyde plus two alcohols; key to sugar ring formation.'),
  ('2026-07-26', 'SILANE', 'organic', true, '矽烷', 'SiH₄ 及其衍生物;半導體 CVD 製程原料。', 'SiH₄ and derivatives; a CVD feedstock in semiconductor fabs.'),
  ('2026-07-27', 'BORANE', 'organic', true, '硼烷', 'BH₃ 及其衍生物,硼氫化反應試劑。', 'BH₃ and derivatives; reagent for hydroboration.'),
  ('2026-07-28', 'TRIOL', 'organic', true, '三元醇', '含三個 –OH 的醇,如甘油。', 'An alcohol with three –OH groups, e.g., glycerol.'),
  ('2026-07-29', 'CRESOL', 'organic', true, '甲酚', '甲基酚,消毒水的成分之一。', 'Methylphenol; a component of disinfectants.'),
  ('2026-07-30', 'FURAN', 'organic', true, '呋喃', '含氧的五員芳香環。', 'A five-membered aromatic ring containing oxygen.'),
  ('2026-07-31', 'PURINE', 'organic', true, '嘌呤', '腺嘌呤、鳥嘌呤的母核,DNA 鹼基。', 'Parent ring of adenine and guanine, DNA bases.'),
  ('2026-08-01', 'TRIMER', 'organic', true, '三聚體', '三個單體結合而成的分子。', 'A molecule formed from three monomers.'),
  ('2026-08-02', 'OXALIC', 'organic', true, '草酸的', '(COOH)₂,菠菜含量高,會與鈣結合。', '(COOH)₂; abundant in spinach, binds calcium.'),
  ('2026-08-03', 'CITRIC', 'organic', true, '檸檬酸的', '檸檬酸循環(TCA)的核心分子。', 'Central molecule of the citric acid (TCA) cycle.'),
  ('2026-08-04', 'LACTIC', 'organic', true, '乳酸的', '運動後肌肉痠痛與優酪乳的酸味來源。', 'Behind post-exercise muscle ache and yogurt''s tang.'),
  ('2026-08-05', 'XYLOSE', 'bio', true, '木糖', '五碳醣,木糖醇的原料。', 'A five-carbon sugar; the precursor of xylitol.'),
  ('2026-08-06', 'HEXOSE', 'bio', true, '六碳醣', '六個碳的單醣,如葡萄糖、果糖。', 'A six-carbon monosaccharide, e.g., glucose, fructose.'),
  ('2026-08-07', 'STEROL', 'bio', true, '固醇', '含四環骨架的脂質,如膽固醇。', 'A lipid with a four-ring core, e.g., cholesterol.'),
  ('2026-08-08', 'GLOBIN', 'bio', true, '球蛋白', '血紅素的蛋白質部分。', 'The protein portion of hemoglobin.'),
  ('2026-08-09', 'LIPASE', 'bio', true, '脂解酶', '分解脂肪為脂肪酸與甘油的酵素。', 'Enzyme that breaks fats into fatty acids and glycerol.'),
  ('2026-08-10', 'CODON', 'bio', true, '密碼子', 'mRNA 上三個鹼基一組,對應一個胺基酸。', 'Three mRNA bases coding for one amino acid.'),
  ('2026-08-11', 'STARCH', 'bio', true, '澱粉', '葡萄糖聚合而成的儲存多醣。', 'A storage polysaccharide made of glucose units.'),
  ('2026-08-12', 'PECTIN', 'bio', true, '果膠', '植物細胞壁的多醣,果醬凝固的關鍵。', 'Plant cell-wall polysaccharide that sets jam.'),
  ('2026-08-13', 'CHITIN', 'bio', true, '幾丁質', '甲殼類外骨骼的含氮多醣。', 'Nitrogen-containing polysaccharide in crustacean shells.'),
  ('2026-08-14', 'LYSINE', 'bio', true, '離胺酸', '必需胺基酸,側鏈帶正電。', 'An essential amino acid with a positively charged side chain.'),
  ('2026-08-15', 'SERINE', 'bio', true, '絲胺酸', '側鏈含 –OH 的胺基酸,酵素活性中心常見。', 'Amino acid with an –OH side chain; common in enzyme active sites.'),
  ('2026-08-16', 'VALINE', 'bio', true, '纈胺酸', '支鏈胺基酸(BCAA)之一。', 'One of the branched-chain amino acids (BCAAs).'),
  ('2026-08-17', 'RAYON', 'mat', true, '嫘縈', '再生纖維素纖維,又稱人造絲。', 'Regenerated cellulose fiber, also called artificial silk.'),
  ('2026-08-18', 'LATEX', 'mat', true, '乳膠', '高分子微粒懸浮液,橡膠手套的原料。', 'A suspension of polymer particles; used for rubber gloves.'),
  ('2026-08-19', 'FIBER', 'mat', true, '纖維', '細長的絲狀材料。', 'A long, thin thread-like material.'),
  ('2026-08-20', 'EPOXY', 'mat', true, '環氧樹脂', '含環氧基的熱固性樹脂,強力膠與電路板基材。', 'Thermoset resin with epoxide groups; glues and PCB substrates.'),
  ('2026-08-21', 'DOPANT', 'mat', true, '摻雜物', '加入半導體中改變導電性的微量雜質,如硼、磷。', 'Trace impurity added to a semiconductor, e.g., boron, phosphorus.'),
  ('2026-08-22', 'WAFER', 'mat', true, '晶圓', '半導體製程的矽單晶薄片。', 'A thin slice of single-crystal silicon for chip fabrication.'),
  ('2026-08-23', 'SINTER', 'mat', true, '燒結', '粉末加熱至熔點以下使其結合成塊的製程。', 'Bonding powder into a solid by heating below the melting point.'),
  ('2026-08-24', 'ANNEAL', 'mat', true, '退火', '加熱後緩慢冷卻以消除內應力的熱處理。', 'Heat treatment: heat then cool slowly to relieve internal stress.'),
  ('2026-08-25', 'ZIRCON', 'mat', true, '鋯石', 'ZrSiO₄,耐高溫,也用於地質定年。', 'ZrSiO₄; heat-resistant and used for geological dating.'),
  ('2026-08-26', 'RUTILE', 'mat', true, '金紅石', 'TiO₂ 的一種晶型,白色顏料與光催化劑。', 'A TiO₂ polymorph; white pigment and photocatalyst.'),
  ('2026-08-27', 'GARNET', 'mat', true, '石榴石', '矽酸鹽礦物族,YAG 雷射晶體屬於此類。', 'A silicate mineral family; YAG laser crystals belong here.'),
  ('2026-08-28', 'HALITE', 'mat', true, '岩鹽', 'NaCl 的礦物形式,立方晶系。', 'The mineral form of NaCl; cubic crystal system.'),
  ('2026-08-29', 'CERIUM', 'element', true, '鈰', '最豐富的稀土元素,用於拋光粉與觸媒轉換器。', 'The most abundant rare earth; used in polishing and catalytic converters.'),
  ('2026-08-30', 'CESIUM', 'element', true, '銫', '最活潑的穩定鹼金屬,銫原子鐘定義「秒」。', 'The most reactive stable alkali metal; caesium clocks define the second.'),
  ('2026-08-31', 'INDIUM', 'element', true, '銦', 'ITO 透明導電膜的主要成分。', 'The main component of ITO transparent conductive films.'),
  ('2026-09-01', 'RADON', 'element', true, '氡', '放射性惰性氣體,室內輻射的主要來源。', 'A radioactive noble gas; the main source of indoor radiation.'),
  ('2026-09-02', 'OSMIUM', 'element', true, '鋨', '密度最大的元素之一。', 'One of the densest elements known.'),
  ('2026-09-03', 'BOSON', 'phys-chem', true, '玻色子', '自旋為整數的粒子,可占據同一量子態。', 'Integer-spin particles that can share the same quantum state.'),
  ('2026-09-04', 'DELTA', 'phys-chem', true, 'Δ', '化學上常表示「變化量」,如 ΔH 焓變。', 'In chemistry, denotes a change, e.g., ΔH for enthalpy change.'),
  ('2026-09-05', 'ALPHA', 'phys-chem', true, 'α', 'α 粒子即氦核;α 衰變會放出氦核。', 'An α particle is a helium nucleus, emitted in alpha decay.'),
  ('2026-09-06', 'GAMMA', 'phys-chem', true, 'γ', 'γ 射線是高能電磁波,穿透力最強。', 'γ rays are high-energy photons with the greatest penetrating power.'),
  ('2026-09-07', 'LAMBDA', 'phys-chem', true, 'λ', '波長的符號,光譜學的核心變數。', 'The symbol for wavelength, central to spectroscopy.'),
  ('2026-09-08', 'DECAY', 'phys-chem', true, '衰變', '不穩定原子核自發放出輻射轉變為其他核種。', 'Spontaneous transformation of an unstable nucleus with radiation emission.'),
  ('2026-09-09', 'HYBRID', 'phys-chem', true, '混成', '軌域混成(sp、sp²、sp³)決定分子幾何。', 'Orbital hybridization (sp, sp², sp³) sets molecular geometry.'),
  ('2026-09-10', 'REFLUX', 'reaction', true, '迴流', '加熱使溶劑蒸發後冷凝回流,維持反應溫度。', 'Boiling with condensate returning, holding the reaction at temperature.'),
  ('2026-09-11', 'QUENCH', 'reaction', true, '淬滅', '快速終止反應或急速冷卻。', 'To stop a reaction abruptly, or to cool rapidly.'),
  ('2026-09-12', 'ELUTE', 'reaction', true, '沖提', '用溶劑把吸附在管柱上的物質洗出來。', 'To wash a substance off a column with solvent.'),
  ('2026-09-13', 'DECANT', 'reaction', true, '傾析', '靜置後把上層澄清液倒出,分離沉澱。', 'To pour off the clear upper liquid, leaving the precipitate.'),
  ('2026-09-14', 'PURIFY', 'reaction', true, '純化', '去除雜質以提高純度。', 'To remove impurities and raise purity.'),
  ('2026-09-15', 'DIGEST', 'reaction', true, '消化', '用酸或酵素分解樣品使其溶解。', 'To break down a sample with acid or enzymes until dissolved.'),
  ('2026-09-16', 'DISTIL', 'reaction', true, '蒸餾', '利用沸點差分離液體混合物(英式拼法)。', 'To separate liquids by boiling point (UK spelling of distill).'),
  ('2026-09-17', 'CRACK', 'reaction', true, '裂解', '石化業把長鏈烴打斷成短鏈的製程。', 'The petrochemical process of breaking long hydrocarbons into short ones.'),
  ('2026-09-18', 'REFORM', 'reaction', true, '重組', '催化重組,把直鏈烴轉成芳香烴提高辛烷值。', 'Catalytic reforming: converting straight chains to aromatics to boost octane.'),
  ('2026-09-19', 'BRINE', 'gen', true, '鹵水', '高濃度鹽水。', 'Highly concentrated salt water.'),
  ('2026-09-20', 'SLURRY', 'gen', true, '漿液', '固體顆粒懸浮在液體中的混合物。', 'A mixture of solid particles suspended in a liquid.'),
  ('2026-09-21', 'ALKALI', 'gen', true, '鹼', '可溶於水的鹼性物質,如 NaOH、KOH。', 'A water-soluble base, e.g., NaOH, KOH.'),
  ('2026-09-22', 'BORATE', 'gen', true, '硼酸鹽', '含 BO₃ 或 BO₄ 的鹽類,硼砂是常見例子。', 'Salts containing BO₃ or BO₄; borax is a common example.'),
  ('2026-09-23', 'FROZEN', 'gen', true, '凍結的', '液體降溫至凝固點以下的固態。', 'Solid state reached by cooling below the freezing point.'),
  ('2026-09-24', 'DENSE', 'gen', true, '緻密的', '單位體積的質量大。', 'Having large mass per unit volume.'),
  ('2026-09-25', 'INERT', 'gen', true, '惰性的', '不易參與化學反應,如氬、氦。', 'Reluctant to react chemically, e.g., argon, helium.'),
  ('2026-09-26', 'BASIC', 'gen', true, '鹼性的', 'pH 大於 7。', 'Having a pH greater than 7.'),
  ('2026-09-27', 'TOXIC', 'gen', true, '有毒的', '對生物有害。', 'Harmful to living organisms.'),
  ('2026-09-28', 'STABLE', 'gen', true, '穩定的', '不易分解或反應。', 'Not readily decomposed or reacted.'),
  ('2026-09-29', 'PLANAR', 'gen', true, '平面的', '所有原子在同一平面上,如苯環。', 'All atoms lying in one plane, e.g., the benzene ring.'),
  ('2026-09-30', 'LINEAR', 'gen', true, '線形的', '鍵角 180° 的分子幾何,如 CO₂。', 'Molecular geometry with a 180° bond angle, e.g., CO₂.'),
  ('2026-10-01', 'PHASE', 'gen', true, '相', '物質中物理性質均勻的部分,如固/液/氣三相。', 'A physically uniform portion of matter, e.g., solid, liquid, gas.'),
  ('2026-10-02', 'TRANS', 'gen', true, '反式', '兩個取代基在雙鍵或環的異側。', 'Substituents on opposite sides of a double bond or ring.'),
  ('2026-10-03', 'ASSAY', 'analytical', true, '分析測定', '測定樣品中某成分含量的實驗。', 'An experiment measuring how much of a component a sample contains.'),
  ('2026-10-04', 'BLANK', 'analytical', true, '空白樣', '不含待測物的對照樣品,用來扣除背景。', 'A control sample without analyte, used to subtract background.'),
  ('2026-10-05', 'NORMAL', 'analytical', true, '當量濃度的', '每公升溶液的當量數(N)。', 'Equivalents of solute per litre of solution (N).'),
  ('2026-10-06', 'PROBE', 'analytical', true, '探針', '用來偵測特定訊號的元件或分子。', 'A device or molecule used to detect a specific signal.'),
  ('2026-10-07', 'SENSOR', 'analytical', true, '感測器', '把化學或物理量轉成電訊號的裝置。', 'A device converting a chemical or physical quantity into an electrical signal.'),
  ('2026-10-08', 'FLASK', 'lab', true, '燒瓶', '圓底或錐形的玻璃容器。', 'A round-bottom or conical glass vessel.'),
  ('2026-10-09', 'BURNER', 'lab', true, '本生燈', '實驗室加熱用的燃氣燈。', 'The gas burner used for heating in the lab.'),
  ('2026-10-10', 'MORTAR', 'lab', true, '研缽', '研磨固體樣品的陶瓷或瑪瑙容器。', 'A ceramic or agate bowl for grinding solid samples.'),
  ('2026-10-11', 'PESTLE', 'lab', true, '研杵', '搭配研缽使用的研磨棒。', 'The grinding rod used together with a mortar.'),
  ('2026-10-12', 'FUNNEL', 'lab', true, '漏斗', '導引液體或搭配濾紙過濾的器材。', 'For guiding liquids or holding filter paper.'),
  ('2026-10-13', 'PIPET', 'lab', true, '吸量管', '精確量取液體體積的細管(美式拼法)。', 'A narrow tube for measuring liquid volume precisely (US spelling).'),
  ('2026-10-14', 'BURET', 'lab', true, '滴定管', '滴定時逐滴加入標準液的刻度管。', 'The graduated tube for delivering titrant drop by drop.'),
  ('2026-10-15', 'OCTET', 'gen', true, '八隅體', '八隅體規則:原子傾向讓最外層有 8 個電子。', 'The octet rule: atoms tend to reach eight outer-shell electrons.'),
  ('2026-10-16', 'NOBLE', 'gen', true, '惰性的', '惰性氣體最外層電子已填滿,極不反應。', 'Noble gases have full outer shells and barely react.'),
  ('2026-10-17', 'GROUP', 'gen', true, '族', '週期表的直行,同族元素價電子數相同。', 'A column of the periodic table; same-group elements share valence count.'),
  ('2026-10-18', 'PERIOD', 'gen', true, '週期', '週期表的橫列,同週期元素電子層數相同。', 'A row of the periodic table; same-period elements share shell count.'),
  ('2026-10-19', 'SHELL', 'gen', true, '電子層', '電子繞核運行的能階分層。', 'An energy level in which electrons orbit the nucleus.'),
  ('2026-10-20', 'ORBIT', 'gen', true, '軌道', '電子環繞原子核的路徑(波耳模型)。', 'The path of an electron around the nucleus (Bohr model).'),
  ('2026-10-21', 'MATTER', 'gen', true, '物質', '具有質量並佔據空間的東西。', 'Anything that has mass and occupies space.'),
  ('2026-10-22', 'LEVEL', 'phys-chem', true, '能階', '電子可占據的離散能量狀態。', 'A discrete energy state an electron can occupy.'),
  ('2026-10-23', 'LEWIS', 'gen', true, '路易斯', '路易斯結構用點表示價電子;路易斯酸接受電子對。', 'Lewis structures show valence electrons as dots; a Lewis acid accepts an electron pair.'),
  ('2026-10-24', 'LENGTH', 'gen', true, '鍵長', '兩個成鍵原子核之間的距離。', 'The distance between the nuclei of two bonded atoms.'),
  ('2026-10-25', 'MOMENT', 'phys-chem', true, '矩', '偶極矩衡量分子電荷分布的不對稱程度。', 'Dipole moment measures how unevenly charge is distributed.'),
  ('2026-10-26', 'FERMI', 'phys-chem', true, '費米', '費米能階是電子填滿的最高能階。', 'The Fermi level is the highest energy level filled by electrons.'),
  ('2026-10-27', 'FORMAL', 'gen', true, '形式的', '形式電荷用來判斷哪個路易斯結構較合理。', 'Formal charge helps decide which Lewis structure is more reasonable.'),
  ('2026-10-28', 'BORIDE', 'gen', true, '硼化物', '硼與金屬形成的化合物,硬度極高。', 'Compounds of boron with metals; extremely hard.'),
  ('2026-10-29', 'POTASH', 'gen', true, '碳酸鉀', '含鉀化合物的統稱,主要用作肥料。', 'A general term for potassium compounds, mainly used as fertilizer.'),
  ('2026-10-30', 'CHALK', 'mat', true, '白堊', '主成分為碳酸鈣的軟質沉積岩。', 'A soft sedimentary rock made mostly of calcium carbonate.'),
  ('2026-10-31', 'BRASS', 'mat', true, '黃銅', '銅與鋅的合金。', 'An alloy of copper and zinc.'),
  ('2026-11-01', 'BRONZE', 'mat', true, '青銅', '銅與錫的合金,人類最早的合金之一。', 'An alloy of copper and tin; one of humanity''s earliest alloys.'),
  ('2026-11-02', 'SOLDER', 'mat', true, '焊錫', '低熔點合金,用於接合金屬。', 'A low-melting alloy used to join metals.'),
  ('2026-11-03', 'LITMUS', 'analytical', true, '石蕊', '石蕊試紙:遇酸變紅、遇鹼變藍。', 'Litmus paper turns red in acid and blue in base.'),
  ('2026-11-04', 'DONOR', 'gen', true, '予體', '提供電子對或質子的物種。', 'A species that supplies an electron pair or a proton.'),
  ('2026-11-05', 'EXCESS', 'gen', true, '過量', '反應中沒被完全消耗的試劑。', 'The reagent not fully consumed in a reaction.'),
  ('2026-11-06', 'LIMIT', 'gen', true, '限量', '限量試劑決定反應產物的最大量。', 'The limiting reagent caps how much product can form.'),
  ('2026-11-07', 'ORDER', 'phys-chem', true, '級數', '反應級數描述速率與濃度的關係。', 'Reaction order describes how rate depends on concentration.'),
  ('2026-11-08', 'CHAIN', 'organic', true, '鏈', '連續相接的原子,如碳鏈;也指連鎖反應。', 'A run of connected atoms (carbon chain); also a chain reaction.'),
  ('2026-11-09', 'AGENT', 'reaction', true, '試劑', '引起特定反應的物質,如氧化劑。', 'A substance causing a specific reaction, e.g., an oxidizing agent.'),
  ('2026-11-10', 'KELVIN', 'phys-chem', true, '凱氏溫標', '絕對溫度的 SI 單位(K),0 K 是絕對零度。', 'The SI unit of absolute temperature (K); 0 K is absolute zero.'),
  ('2026-11-11', 'PASCAL', 'phys-chem', true, '帕斯卡', '壓力的 SI 單位(Pa)。', 'The SI unit of pressure (Pa).'),
  ('2026-11-12', 'NEWTON', 'phys-chem', true, '牛頓', '力的 SI 單位(N)。', 'The SI unit of force (N).'),
  ('2026-11-13', 'HERTZ', 'phys-chem', true, '赫茲', '頻率的 SI 單位(Hz),每秒振動次數。', 'The SI unit of frequency (Hz), cycles per second.'),
  ('2026-11-14', 'TESLA', 'phys-chem', true, '特斯拉', '磁場強度單位(T);NMR 儀器常以此標示規格。', 'The unit of magnetic field strength (T); used to rate NMR magnets.'),
  ('2026-11-15', 'DEBYE', 'phys-chem', true, '德拜', '偶極矩的單位(D)。', 'The unit of dipole moment (D).'),
  ('2026-11-16', 'GAUSS', 'phys-chem', true, '高斯', '磁場強度的 CGS 單位,1 T = 10⁴ G。', 'The CGS unit of magnetic field; 1 T = 10⁴ G.'),
  ('2026-11-17', 'FARAD', 'phys-chem', true, '法拉', '電容的 SI 單位(F)。', 'The SI unit of capacitance (F).'),
  ('2026-11-18', 'AMPERE', 'phys-chem', true, '安培', '電流的 SI 單位(A)。', 'The SI unit of electric current (A).'),
  ('2026-11-19', 'DEGREE', 'gen', true, '度', '溫度或角度的度量單位。', 'A unit of temperature or of angle.'),
  ('2026-11-20', 'RAMAN', 'analytical', true, '拉曼', '拉曼光譜量測分子振動造成的散射頻移。', 'Raman spectroscopy measures scattering shifts from molecular vibrations.'),
  ('2026-11-21', 'EXCITE', 'phys-chem', true, '激發', '讓電子從低能階躍遷到高能階。', 'To promote an electron from a lower to a higher energy level.'),
  ('2026-11-22', 'GROUND', 'phys-chem', true, '基態', '基態是能量最低、最穩定的狀態。', 'The ground state is the lowest-energy, most stable state.'),
  ('2026-11-23', 'SHIFT', 'analytical', true, '位移', '化學位移(δ)是 NMR 判別官能基的關鍵。', 'Chemical shift (δ) is how NMR distinguishes functional groups.'),
  ('2026-11-24', 'FIELD', 'phys-chem', true, '場', '磁場或電場;NMR 的磁場強度決定解析度。', 'A magnetic or electric field; NMR field strength sets resolution.'),
  ('2026-11-25', 'SIGNAL', 'analytical', true, '訊號', '儀器偵測到的輸出,通常與濃度成正比。', 'The instrument output, usually proportional to concentration.'),
  ('2026-11-26', 'NOISE', 'analytical', true, '雜訊', '訊號中的隨機干擾,決定偵測極限。', 'Random interference in a signal; sets the detection limit.'),
  ('2026-11-27', 'MATRIX', 'analytical', true, '基質', '樣品中除了待測物以外的所有成分。', 'Everything in a sample other than the analyte.'),
  ('2026-11-28', 'TORCH', 'analytical', true, '炬管', 'ICP 的石英炬管,產生高溫電漿。', 'The quartz torch in ICP that generates the hot plasma.'),
  ('2026-11-29', 'SAMPLE', 'analytical', true, '樣品', '拿來分析的那一份物質。', 'The portion of material taken for analysis.'),
  ('2026-11-30', 'INJECT', 'analytical', true, '注射', '把樣品導入儀器的動作。', 'Introducing the sample into the instrument.'),
  ('2026-12-01', 'DETECT', 'analytical', true, '偵測', '找出並量測目標物的存在。', 'To find and measure the presence of a target substance.'),
  ('2026-12-02', 'TRACE', 'analytical', true, '微量', '極低濃度的成分,常以 ppm 或 ppb 表示。', 'A component at very low concentration, often ppm or ppb.'),
  ('2026-12-03', 'DILUTE', 'gen', true, '稀釋', '加入溶劑降低濃度。', 'To lower concentration by adding solvent.'),
  ('2026-12-04', 'STOCK', 'analytical', true, '儲備液', '高濃度的母液,使用時再稀釋。', 'A concentrated solution diluted before use.'),
  ('2026-12-05', 'WEIGH', 'lab', true, '秤重', '用天平測定質量。', 'To measure mass with a balance.'),
  ('2026-12-06', 'PLATE', 'analytical', true, '板', '薄層層析的板;理論板數也用來衡量管柱效率。', 'A TLC plate; "plates" also measure column efficiency.'),
  ('2026-12-07', 'CHARGE', 'gen', true, '電荷', '離子或粒子所帶的電量。', 'The amount of electricity carried by an ion or particle.'),
  ('2026-12-08', 'PURGE', 'lab', true, '吹淨', '通入惰性氣體趕走空氣或揮發物。', 'Sweeping out air or volatiles with an inert gas.'),
  ('2026-12-09', 'RINSE', 'lab', true, '潤洗', '用溶劑沖洗器皿或管柱。', 'Washing glassware or a column with solvent.'),
  ('2026-12-10', 'SEPTUM', 'lab', true, '隔膜', '可被針頭刺穿又能自封的橡膠墊片。', 'A rubber disc a needle can pierce that reseals itself.'),
  ('2026-12-11', 'SPIKE', 'analytical', true, '加標', '刻意加入已知量的標準品以驗證回收率。', 'Adding a known amount of standard to check recovery.'),
  ('2026-12-12', 'CURVE', 'analytical', true, '曲線', '檢量線:濃度對訊號的關係圖。', 'A calibration curve plots signal against concentration.'),
  ('2026-12-13', 'SLOPE', 'analytical', true, '斜率', '檢量線的斜率代表方法的靈敏度。', 'The calibration slope represents method sensitivity.'),
  ('2026-12-14', 'RANGE', 'analytical', true, '範圍', '方法可準確定量的濃度區間。', 'The concentration span over which a method is accurate.'),
  ('2026-12-15', 'GIBBS', 'phys-chem', true, '吉布斯', '吉布斯自由能 ΔG 判斷反應是否自發。', 'Gibbs free energy ΔG tells whether a reaction is spontaneous.'),
  ('2026-12-16', 'STATE', 'phys-chem', true, '狀態', '由溫度、壓力等決定的系統條件;狀態函數與路徑無關。', 'A system''s condition set by T, P, etc.; state functions are path-independent.'),
  ('2026-12-17', 'CYCLE', 'phys-chem', true, '循環', '回到初始狀態的一連串過程,如卡諾循環。', 'A series of processes returning to the starting state, e.g., the Carnot cycle.'),
  ('2026-12-18', 'FREEZE', 'gen', true, '凝固', '液體降溫轉為固體。', 'A liquid turning solid on cooling.'),
  ('2026-12-19', 'TEMPER', 'mat', true, '回火', '淬火後再加熱至較低溫,降低脆性。', 'Reheating after quenching to reduce brittleness.'),
  ('2026-12-20', 'IDEAL', 'phys-chem', true, '理想的', '理想氣體假設分子無體積、無交互作用。', 'An ideal gas has no molecular volume and no interactions.'),
  ('2026-12-21', 'FLUID', 'gen', true, '流體', '可流動的物質,包含液體與氣體。', 'A substance that flows — liquids and gases.'),
  ('2026-12-22', 'ADSORB', 'phys-chem', true, '吸附', '分子附著在固體表面(不是進入內部)。', 'Molecules sticking to a solid surface (not entering the bulk).'),
  ('2026-12-23', 'DESORB', 'phys-chem', true, '脫附', '吸附的分子離開表面。', 'Adsorbed molecules leaving the surface.'),
  ('2026-12-24', 'UPTAKE', 'phys-chem', true, '吸收量', '材料所能吸附或儲存的量。', 'How much a material can adsorb or store.'),
  ('2026-12-25', 'POISON', 'reaction', true, '毒化', '雜質吸附在催化劑活性位點使其失效。', 'An impurity that blocks a catalyst''s active sites.'),
  ('2026-12-26', 'BUBBLE', 'gen', true, '氣泡', '液體中的氣體球;通氣常用於反應或除氧。', 'A gas sphere in liquid; bubbling is used to react or deoxygenate.'),
  ('2026-12-27', 'PLANE', 'mat', true, '晶面', '晶體中由米勒指數描述的原子平面。', 'An atomic plane in a crystal, described by Miller indices.'),
  ('2026-12-28', 'FACET', 'mat', true, '晶面', '晶體外露的平整表面,不同晶面催化活性不同。', 'An exposed flat crystal face; different facets differ in catalytic activity.'),
  ('2026-12-29', 'GRAIN', 'mat', true, '晶粒', '多晶材料中方向一致的小晶區。', 'A small region of uniform orientation in a polycrystal.'),
  ('2026-12-30', 'DOMAIN', 'mat', true, '疇區', '性質一致的微小區域,如磁疇。', 'A microscopic region of uniform property, e.g., a magnetic domain.'),
  ('2026-12-31', 'DEFECT', 'mat', true, '缺陷', '晶格中的不完美處,如空位、雜質。', 'An imperfection in a lattice, e.g., a vacancy or impurity.'),
  ('2027-01-01', 'ORTHO', 'organic', true, '鄰位', '苯環上相鄰兩個取代基的相對位置。', 'The relative position of two adjacent substituents on a benzene ring.'),
  ('2027-01-02', 'GLASSY', 'mat', true, '玻璃態的', '原子排列無長程秩序的非晶態。', 'An amorphous state with no long-range atomic order.'),
  ('2027-01-03', 'CURING', 'mat', true, '固化', '高分子交聯硬化的過程,如環氧樹脂。', 'The crosslinking process that hardens a polymer, e.g., epoxy.'),
  ('2027-01-04', 'MOULD', 'mat', true, '模具', '成型高分子用的模子(英式拼法)。', 'The form used to shape a polymer (UK spelling of mold).'),
  ('2027-01-05', 'TOUGH', 'mat', true, '韌的', '能吸收大量能量而不斷裂。', 'Able to absorb a lot of energy before fracturing.'),
  ('2027-01-06', 'RIGID', 'mat', true, '剛硬的', '不易形變。', 'Not easily deformed.'),
  ('2027-01-07', 'CREEP', 'mat', true, '潛變', '材料在長期定負荷下緩慢變形。', 'Slow deformation under a constant long-term load.'),
  ('2027-01-08', 'POLYOL', 'organic', true, '多元醇', '含多個 –OH 的化合物,聚氨酯的原料。', 'A compound with many –OH groups; a feedstock for polyurethane.'),
  ('2027-01-09', 'STEEL', 'mat', true, '鋼', '鐵碳合金,含碳量低於 2%。', 'An iron–carbon alloy containing less than 2% carbon.'),
  ('2027-01-10', 'CEMENT', 'mat', true, '水泥', '加水後硬化的膠結材料,混凝土的黏著劑。', 'A binder that hardens with water; the glue in concrete.'),
  ('2027-01-11', 'ENAMEL', 'mat', true, '琺瑯', '燒附在金屬表面的玻璃質塗層。', 'A glassy coating fused onto metal.'),
  ('2027-01-12', 'LAYER', 'mat', true, '層', '材料中的一個厚度區段,如石墨的層狀結構。', 'A thickness section of material, e.g., graphite''s layered structure.'),
  ('2027-01-13', 'PELLET', 'mat', true, '顆粒', '壓製成型的小圓粒,催化劑常做成此形。', 'A small compressed granule; a common catalyst form.'),
  ('2027-01-14', 'POWDER', 'mat', true, '粉末', '細碎的固體顆粒。', 'Finely divided solid particles.'),
  ('2027-01-15', 'FLAKE', 'mat', true, '薄片', '片狀的固體,如石墨片。', 'A thin plate-like solid, e.g., a graphite flake.'),
  ('2027-01-16', 'SHEET', 'mat', true, '片', '平整的薄層材料,如石墨烯單層。', 'A flat thin layer of material, e.g., a graphene sheet.'),
  ('2027-01-17', 'DIESEL', 'mat', true, '柴油', '沸點比汽油高的燃料餾分。', 'A fuel fraction boiling higher than gasoline.'),
  ('2027-01-18', 'PETROL', 'mat', true, '汽油', '汽油的英式說法,美式為 gasoline。', 'Gasoline (UK term).'),
  ('2027-01-19', 'REFINE', 'reaction', true, '精煉', '把原油分餾並純化成各種產品。', 'Fractionating and purifying crude oil into products.'),
  ('2027-01-20', 'OLEFIN', 'organic', true, '烯烴', '烯烴的工業用語,即 alkene。', 'The industrial term for an alkene.'),
  ('2027-01-21', 'URACIL', 'bio', true, '尿嘧啶', 'RNA 特有的鹼基,DNA 中由胸腺嘧啶取代。', 'The RNA-specific base, replaced by thymine in DNA.'),
  ('2027-01-22', 'STRAND', 'bio', true, '股', '雙股 DNA 的其中一條。', 'One of the two chains in double-stranded DNA.'),
  ('2027-01-23', 'GENOME', 'bio', true, '基因體', '一個生物全部的遺傳訊息。', 'The complete genetic information of an organism.'),
  ('2027-01-24', 'ACTIN', 'bio', true, '肌動蛋白', '構成細胞骨架與肌肉的球狀蛋白。', 'A globular protein forming the cytoskeleton and muscle.'),
  ('2027-01-25', 'MYOSIN', 'bio', true, '肌凝蛋白', '與肌動蛋白一起產生肌肉收縮的馬達蛋白。', 'A motor protein that works with actin to contract muscle.'),
  ('2027-01-26', 'LIGASE', 'bio', true, '連接酶', '把兩段 DNA 接起來的酵素。', 'The enzyme that joins two DNA fragments.'),
  ('2027-01-27', 'KINASE', 'bio', true, '激酶', '把磷酸基轉移到其他分子的酵素。', 'An enzyme that transfers a phosphate group to another molecule.'),
  ('2027-01-28', 'OLEIC', 'organic', true, '油酸的', '油酸是橄欖油的主要單元不飽和脂肪酸。', 'Oleic acid is the main monounsaturated fat in olive oil.'),
  ('2027-01-29', 'OLEATE', 'organic', true, '油酸鹽', '油酸的鹽或酯,肥皂的成分之一。', 'A salt or ester of oleic acid; a soap component.'),
  ('2027-01-30', 'MOIETY', 'organic', true, '基團', '分子中具有特定性質的一部分。', 'A distinct portion of a molecule with characteristic behaviour.'),
  ('2027-01-31', 'CYCLIC', 'organic', true, '環狀的', '原子接成環的結構,如環己烷。', 'A structure whose atoms form a ring, e.g., cyclohexane.'),
  ('2027-02-01', 'MIXING', 'reaction', true, '混合', '把不同物質攪拌均勻。', 'Stirring different substances until uniform.'),
  ('2027-02-02', 'AGING', 'mat', true, '熟成', '材料隨時間改變性質的過程。', 'A material''s properties changing over time.'),
  ('2027-02-03', 'SETTLE', 'reaction', true, '沉降', '固體顆粒因重力沉到底部。', 'Solid particles sinking under gravity.'),
  ('2027-02-04', 'IMPURE', 'gen', true, '不純的', '含有雜質。', 'Containing impurities.'),
  ('2027-02-05', 'DIODE', 'mat', true, '二極體', '只讓電流單向通過的半導體元件。', 'A semiconductor device that passes current one way only.'),
  ('2027-02-06', 'BIOGAS', 'gen', true, '沼氣', '有機物厭氧分解產生的甲烷混合氣。', 'Methane-rich gas from anaerobic decomposition of organic matter.'),
  ('2027-02-07', 'SOLAR', 'gen', true, '太陽能的', '來自太陽的能量,綠色化學的重要能源。', 'Energy from the sun; a key green-chemistry energy source.'),
  ('2027-02-08', 'SLUDGE', 'gen', true, '污泥', '廢水處理沉澱下來的半固體。', 'The semi-solid settled out in wastewater treatment.'),
  ('2027-02-09', 'SEWAGE', 'gen', true, '污水', '生活或工業排放的廢水。', 'Wastewater discharged from homes or industry.'),
  ('2027-02-10', 'LEACH', 'gen', true, '淋溶', '用液體把固體中的成分溶出來。', 'Dissolving components out of a solid with a liquid.'),
  ('2027-02-11', 'RUNOFF', 'gen', true, '逕流', '沖刷地表流入水體的水,常帶著污染物。', 'Surface water flowing into waterways, often carrying pollutants.'),
  ('2027-02-12', 'BENIGN', 'gen', true, '良性的', '綠色化學強調「設計上就無害」。', 'Green chemistry aims for substances that are benign by design.'),
  ('2027-02-13', 'RENEW', 'gen', true, '更新', '可再生資源能夠自然補充。', 'Renewable resources replenish naturally.'),
  ('2027-02-14', 'REUSE', 'gen', true, '再利用', '重複使用而不丟棄。', 'Using again rather than discarding.'),
  ('2027-02-15', 'TOXIN', 'gen', true, '毒素', '生物產生的有毒物質。', 'A poisonous substance produced by a living organism.'),
  ('2027-02-16', 'HAZARD', 'gen', true, '危害', '可能造成傷害的來源。', 'A source of potential harm.'),
  ('2027-02-17', 'SAFETY', 'lab', true, '安全', '實驗室操作的首要原則。', 'The first principle of laboratory work.'),
  ('2027-02-18', 'EXPOSE', 'gen', true, '暴露', '接觸到有害物質或輻射。', 'Coming into contact with a harmful substance or radiation.'),
  ('2027-02-19', 'DOSAGE', 'gen', true, '劑量', '接觸或服用的量,決定毒性大小。', 'The amount received; it determines toxicity.'),
  ('2027-02-20', 'INTAKE', 'gen', true, '攝入量', '進入體內的物質總量。', 'The total amount of a substance taken into the body.'),
  ('2027-02-21', 'SMOKE', 'gen', true, '煙', '燃燒產生的固體微粒懸浮於氣體中。', 'Solid particles from combustion suspended in gas.'),
  ('2027-02-22', 'DRYING', 'lab', true, '乾燥', '去除樣品中的水分。', 'Removing moisture from a sample.');


-- ─── 訪客池(40 題,puzzle_date 必須為 null) ───
insert into public.daily_puzzles
  (puzzle_date, answer, category, is_active, is_guest_pool, zh_name, zh_description, en_description)
values
  (null, 'OCTANE', 'organic', true, true, '辛烷', 'C₈H₁₈,八碳烷烴;汽油辛烷值的基準物。', 'C₈H₁₈; eight-carbon alkane, the reference for octane rating.'),
  (null, 'PHENYL', 'organic', true, true, '苯基', 'C₆H₅–,苯少一個氫的基團。', 'C₆H₅–; benzene minus one hydrogen.'),
  (null, 'XYLENE', 'organic', true, true, '二甲苯', 'C₈H₁₀,苯環接兩個甲基,有鄰/間/對三種。', 'C₈H₁₀; benzene with two methyls — ortho, meta, para.'),
  (null, 'ACETIC', 'organic', true, true, '醋酸的', '乙酸 CH₃COOH,食用醋的酸味來源。', 'Acetic acid CH₃COOH; what makes vinegar sour.'),
  (null, 'RIBOSE', 'bio', true, true, '核糖', 'RNA 的五碳醣骨架。', 'The five-carbon sugar backbone of RNA.'),
  (null, 'NYLON', 'mat', true, true, '尼龍', '聚醯胺纖維,第一個商業化的合成纖維。', 'Polyamide fiber; the first commercial synthetic fiber.'),
  (null, 'GYPSUM', 'mat', true, true, '石膏', 'CaSO₄·2H₂O,建材與模型材料。', 'CaSO₄·2H₂O; used in construction and casting.'),
  (null, 'BARIUM', 'element', true, true, '鋇', '第 2 族鹼土金屬,硫酸鋇是腸胃 X 光顯影劑。', 'Group 2 alkaline earth metal; BaSO₄ is a GI X-ray contrast agent.'),
  (null, 'QUARK', 'phys-chem', true, true, '夸克', '組成質子與中子的基本粒子。', 'Elementary particles that make up protons and neutrons.'),
  (null, 'REDOX', 'reaction', true, true, '氧化還原', '電子轉移反應的總稱。', 'The umbrella term for electron-transfer reactions.'),
  (null, 'SALINE', 'gen', true, true, '生理食鹽水', '0.9% NaCl 水溶液,與體液等滲。', '0.9% NaCl solution, isotonic with body fluids.'),
  (null, 'MOLTEN', 'gen', true, true, '熔融的', '固體加熱至熔點以上的液態。', 'Liquid state of a solid heated above its melting point.'),
  (null, 'PURITY', 'analytical', true, true, '純度', '目標物佔總量的比例。', 'The fraction of the total that is the target substance.'),
  (null, 'BEAKER', 'lab', true, true, '燒杯', '圓柱形平底玻璃容器,最常見的實驗器皿。', 'A flat-bottomed cylindrical glass vessel; the classic lab container.'),
  (null, 'ANION', 'gen', true, true, '陰離子', '帶負電的離子,原子得到電子後形成。', 'A negatively charged ion, formed by gaining electrons.'),
  (null, 'ANGLE', 'gen', true, true, '鍵角', '兩個化學鍵之間的夾角,如水的 104.5°。', 'The angle between two bonds, e.g., 104.5° in water.'),
  (null, 'BORAX', 'gen', true, true, '硼砂', 'Na₂B₄O₇·10H₂O,清潔劑與玻璃原料。', 'Na₂B₄O₇·10H₂O; used in cleaners and glassmaking.'),
  (null, 'STRONG', 'gen', true, true, '強的', '強酸強鹼在水中完全解離。', 'Strong acids and bases dissociate completely in water.'),
  (null, 'JOULE', 'phys-chem', true, true, '焦耳', '能量的 SI 單位(J)。', 'The SI unit of energy (J).'),
  (null, 'ABSORB', 'phys-chem', true, true, '吸收', '物質吸收特定波長的光,是吸收光譜的基礎。', 'Matter taking in light at specific wavelengths — the basis of absorption spectroscopy.'),
  (null, 'COLUMN', 'analytical', true, true, '管柱', '層析用的填充管,分離混合物的核心元件。', 'The packed tube in chromatography where separation happens.'),
  (null, 'SYSTEM', 'phys-chem', true, true, '系統', '熱力學中被研究的那一部分,其餘稱為環境。', 'The part under study in thermodynamics; the rest is the surroundings.'),
  (null, 'ACTIVE', 'reaction', true, true, '活性的', '活性位點是催化劑上真正發生反應的地方。', 'The active site is where the reaction actually occurs on a catalyst.'),
  (null, 'CUBIC', 'mat', true, true, '立方的', '立方晶系,如 NaCl 的面心立方結構。', 'The cubic crystal system, e.g., NaCl''s face-centred cubic lattice.'),
  (null, 'BLEND', 'mat', true, true, '摻合', '把兩種以上高分子混合以調整性質。', 'Mixing two or more polymers to tune properties.'),
  (null, 'GLASS', 'mat', true, true, '玻璃', '主成分為二氧化矽的非晶質固體。', 'An amorphous solid made mainly of silica.'),
  (null, 'CRUDE', 'mat', true, true, '原油', '未經精煉的石油。', 'Unrefined petroleum.'),
  (null, 'HELIX', 'bio', true, true, '螺旋', 'DNA 雙股螺旋、蛋白質 α 螺旋的結構。', 'The DNA double helix and the protein α-helix.'),
  (null, 'BRANCH', 'organic', true, true, '支鏈', '從主鏈分出去的碳鏈。', 'A carbon chain splitting off the main chain.'),
  (null, 'WASTE', 'gen', true, true, '廢棄物', '製程中產生、不需要的物質。', 'Unwanted material generated by a process.'),
  (null, 'ALKANE', 'organic', true, true, '烷烴', '只含 C–C 單鍵的飽和烴,通式 CₙH₂ₙ₊₂。', 'Saturated hydrocarbons with only C–C single bonds (CₙH₂ₙ₊₂).'),
  (null, 'NITRO', 'organic', true, true, '硝基', '–NO₂,TNT 炸藥的關鍵官能基。', '–NO₂; the key group in TNT explosives.'),
  (null, 'DIMER', 'organic', true, true, '二聚體', '兩個相同單體結合而成的分子。', 'A molecule formed from two identical monomers.'),
  (null, 'FORMIC', 'organic', true, true, '蟻酸的', '甲酸 HCOOH,螞蟻分泌的最簡單羧酸。', 'Formic acid HCOOH; the simplest carboxylic acid, from ants.'),
  (null, 'PEPSIN', 'bio', true, true, '胃蛋白酶', '胃液中分解蛋白質的酵素,最適 pH 約 2。', 'Stomach enzyme that digests protein; optimal near pH 2.'),
  (null, 'RESIN', 'mat', true, true, '樹脂', '天然或合成的黏稠高分子材料。', 'A viscous natural or synthetic polymer material.'),
  (null, 'PYRITE', 'mat', true, true, '黃鐵礦', 'FeS₂,金屬光澤似黃金,俗稱愚人金。', 'FeS₂; metallic lustre resembling gold — "fool''s gold".'),
  (null, 'RADIUM', 'element', true, true, '鐳', '居禮夫人發現的放射性元素。', 'The radioactive element discovered by Marie Curie.'),
  (null, 'SIGMA', 'phys-chem', true, true, 'σ', 'σ 鍵是沿鍵軸重疊形成的單鍵。', 'A σ bond forms by head-on overlap along the bond axis.'),
  (null, 'FILTER', 'reaction', true, true, '過濾', '用濾材分離固體與液體。', 'To separate solid from liquid using a filter medium.');


-- ─── 重洗所有學生的 queue(讓新題目進入輪替) ───
delete from public.guess_sessions where is_complete = false;
truncate public.student_puzzle_queues;

do $$
declare v_student record;
begin
  for v_student in select id from public.students loop
    perform public.shuffle_round_for_student(v_student.id);
  end loop;
end$$;

commit;


-- ─── 驗證(交易外,跑完看這個) ───
select
  (select count(*) from public.daily_puzzles where is_guest_pool=false and is_active=true) as daily_active,
  (select count(*) from public.daily_puzzles where is_guest_pool=true  and is_active=true) as guest_active,
  (select count(*) from public.valid_words) as dictionary_size,
  (select count(distinct student_id) from public.student_puzzle_queues) as students_reshuffled;
-- 預期:
--   daily_active ≈ 307(原 74 + 本次 233)
--   guest_active ≈ 66(原 26 + 本次 40)
